### ISSUE TITLE
[Bug]: Improper behavior

### ISSUE THREAD

**Issue by hugomarins** [coldenate/rollover-daily-todos#5] opened 2023-08-23 20:40 UTC
### What happened?

Automatic rollover does not happen for me. 

Because of this, I tried the \rollover command, but an unwanted thing happened: The daily docs itself were rolled underneath the present day, instead of only the unfinifhed todos, and now those daily docs were permanently moved from the regular daily docs powerup page, and this cannot be undone.

![image](https://github.com/coldenate/rollover-daily-todos/assets/54500828/35269926-31eb-4feb-81e0-ece6158a978c)

![image](https://github.com/coldenate/rollover-daily-todos/assets/54500828/9262af0e-a2e4-41c2-9cd2-3d1f77e6def1)

### Code of Conduct

- [x] I agree

**Comment by coldenate** [comment] 2023-08-24 00:27
Thank you!! I'll take a look into this. Multiple people are also having this issue so I'm glad there is extra context! 😄

**Comment by coldenate** [comment] 2023-08-25 21:50
Hey @hugomarins! I have a quick question, were you watching the time waiting for them to rollover? Like staying in the app until they rollover? I failed to mention in my initial posting of the plugin that the current functionality is a check system, so when the `autoRollover` event is triggered it can do the rolling over, but I have not yet made it live update-compatible. 
Because of this, I can't *exactly* reproduce the issue yet, but I think I understand why it may be confusing. So, I'll definitely be considering adding that live-rollover option. It makes sense!

**Comment by coldenate** [comment] 2023-08-25 21:51
I also can't reproduce the daily docs themselves being moved up into the rem itself. Could you show me what your rems looked like before? Are you able to make that bug happen again?

**Comment by coldenate** [comment] 2023-08-25 21:52
I'm planning on changing the behavior to portalling rems in instead of actually moving them, so maybe it is a RemNote version incompatibility thing. What are your app specifics?

**Comment by hugomarins** [comment] 2023-08-26 17:54
What I tried to say is that my to-dos never rolled. At first, it was set to 00:00h. After a few days, I saw automatic rolling was not happening. Then I set the time to that time and watched to see if something will happen. But it did not. That's why I tried to force the rolling over using the \rollover command.

**Comment by hugomarins** [comment] 2023-08-26 18:08
I tried to reproduce the bug, but now nothing happens when I use the  \rollover command.

**Comment by coldenate** [comment] 2023-08-27 01:55
Oh ok. @hugomarins There is a softlock to how many days back it looks, and the default is set to 7 days. **Could you try setting the days it looks back in time to a greater value?** 
I'm going to push a hotfix right now, if you have issues with it further, please let me know.

## Methodology to test the automatic time

1. Set the setting to a time that you can test (it has to be greater than the time currently. for ex. do a minute forward)
2. run `/debug auto rollover`
3. wait for the set time to roll in, then it will roll over.

changing the setting will not tell RTD that it is a new day. if it has already run in the current day, it will not at all for the rest of that day unless the slash command is used.

**Comment by coldenate** [comment] 2023-08-27 19:42
The issue of not automatically rolling over was resolved in 917ba2f. Please reopen if you are still having issues 😄

have a great day!

**Closed as completed by coldenate** 2023-08-27 19:42 UTC
Labels: bug, enhancement

**Comment by hugomarins** [comment] 2023-08-28 08:22
Yeap, working perfectly now. The idea of portals was terrific! Thanks for your efforts!
