### ISSUE TITLE
Tasks do not rollover more than once from previous day

### ISSUE THREAD

**Issue by anumeha-in** [coldenate/rollover-daily-todos#8] opened 2023-09-06 01:32 UTC
Hello,
Thanks for the plugin, it has helped me stay on top of my work tasks. I would like to report a bug - tasks rollover only once from the previous day. If they remain unfinished, they stay in that daily document instead of rolling over to the new daily document. So it is easy to miss older incomplete tasks. 
[enhancement] Similar to the to-dos that are created during the day in other documents are added into the daily document in real-time, it would be great, if the previous day or unfinished tasks rollover in addition to the set 24-hr. time window to sync-up. Love the feature where tasks get added into the daily document portal as soon as they are added to other rems.

**Comment by coldenate** [comment] 2023-09-09 22:16
Hi there! @anumeha-in  I'm so glad this plugin helps your workflow! :)

1. I believe the bug you found might be a feature, and I'd like to know a little bit more about the issue. 
   - I was not able to reproduce this error; please supply the following information for troubleshooting.
       - plugin version
       - app version
       - What is your settings for `Date Formatting` and `Time Formatting` in the RemNote settings?
          - You can find this by searching "date" in the RN settings
   - RDT by default only checks the past **7** daily documents for unfinished todos. This is to help mitigate stale todos, but I see your point in them being easily forgotten. 
   - Was the daily document that was ignored from the day before? How long ago was it?
2. I love your enhancement idea! I have some questions to clarify:
   - Are you saying that tasks created anywhere can also be portaled in?
   - >  if the previous day or unfinished tasks rollover in addition to the set 24-hr. time window to sync-up. 
     - that is supposed to happen 😅. That might be a bug. Could you provide an example or some explanation as to what you expect? If an unfinished todo is detected from the previous day, it is *supposed* to rollover. 

Thanks!

**Comment by coldenate** [comment] 2023-09-15 01:18
In summary, if it has rolled over a task for seven days in a row, the source document is past the threshold. Is this your case? If the portals lead to a daily document that's date is more than seven days ago, RTD will **not** rollover that task unless you modify the settings. 
So if you want to break the seven days requirement, you can do the following:

1. Manually move the todos from the daily document to the recent document
2. Increase the threshold in the plugin settings
3. Switch from portal mode to non-portal-mode. This makes the plugin do option 1 for you. 

I'll close this for now as based on my understanding of the issue this is a feature, but I may be missing something in your issue description.

**Comment by anumeha-in** [comment] 2023-09-23 05:54
Hi Nathan,
Sorry, I was out so couldn't respond earlier. I am using Remnote version 1.12.4, and plugin version 1.3.0. Below are the settings I use for the plugin and Remnote date/time.

![image](https://github.com/coldenate/rollover-daily-todos/assets/144189642/7bf6743d-a57a-46d1-ad6c-07f3e8c40098)
![image](https://github.com/coldenate/rollover-daily-todos/assets/144189642/2ca664ad-1dc2-4efb-a29f-677b6fdce735)

The stale documents are from the previous day and days before that. My setting is to look back 60 days, the current daily doc still doesn't show them rolled over. 
![image](https://github.com/coldenate/rollover-daily-todos/assets/144189642/d2c1c78a-6013-41d7-bee8-ae95c2df5038)

Previous ToDos: 
Snapshot of the tasks rolled over from Aug 31st to Sep 1. But it did not rollover to Sep 2 or beyond even though it was not complete.
![image](https://github.com/coldenate/rollover-daily-todos/assets/144189642/d3d1eeb7-a9af-4bfb-a533-7885ff1d07bf)
![image](https://github.com/coldenate/rollover-daily-todos/assets/144189642/c36ee529-0c02-4353-9e53-0ee415fa47d4)

Reg. "if the previous day or unfinished tasks rollover in addition to the set 24-hr. time window to sync-up." My apologies if I wasn't clear. I meant here that the tasks roll over should happen as soon as I open daily document, rather than waiting for the fixed daily sync up time. This is similar to how the tasks created elsewhere get portaled into the daily document in real-time.

**Comment by coldenate** [comment] 2023-09-23 20:23
No problem! Thank you for responding. I'm assuming you meant `Version 1.12.40` and not `Version 1.12.4`...? If you are on ..4, I would really suggest updating RemNote to the latest version. 😅
I'm wondering if the plugin has messed up storing the last autoRollover time in your account. I've just pushed an update that introduces a Debug mode. Head to settings, check Debug Mode, and restart the app. 
<img width="895" alt="image" src="https://github.com/coldenate/rollover-daily-todos/assets/66754842/66fc455e-e5c8-4867-9916-f555cd58b704">

Then run the following commands:
1. `/log values` (then send screenshot of the toast, and the console output)
2. Set the time to rollover to the next 2 minutes
3. `/Debug Auto Rollover` 
4. `/log values` (then send screenshot of the toast, and the console output)

I'm wondering if there is something stuck in the session storage... 🤔

> Reg. "if the previous day or unfinished tasks rollover in addition to the set 24-hr. time window to sync-up." My apologies if I wasn't clear. I meant here that the tasks roll over should happen as soon as I open daily document, rather than waiting for the fixed daily sync up time. This is similar to how the tasks created elsewhere get portaled into the daily document in real-time.

Got it. I like the idea! Like a "if Daily Doc is opened", "run the rollover".

**Comment by anumeha-in** [comment] 2023-09-24 17:20
Hi Nathan,
I am not sure where to run the commands you mentioned above. Any pointers would be helpful :-)
Also, the full version is 1.12.42-beta

**Comment by coldenate** [comment] 2023-09-24 19:40
@anumeha-in My apologies! You can run those commands anywhere in RemNote. You can run them in the Omnibus, or you can run them in any rem editor.

**Comment by anumeha-in** [comment] 2023-09-25 06:11
Thanks! It rolled over the pending tasks from past To-Dos. Here are the screenshots as requested.
![Screenshot 2023-09-24 223914](https://github.com/coldenate/rollover-daily-todos/assets/144189642/b9f9a6f3-86c2-4ffe-9f41-d6995ccb7ae5)
![Screenshot 2023-09-24 224041](https://github.com/coldenate/rollover-daily-todos/assets/144189642/51f619e4-2437-4966-b737-d74490dacb24)
![Screenshot 2023-09-24 224118](https://github.com/coldenate/rollover-daily-todos/assets/144189642/79846e84-4516-4bd8-8477-0b69873252c3)

I then created a new to-do task with past due date of Sep 20th and re-ran the sync-up. The task did not move to today's doc. I tried the above-mentioned steps couple times, incl. changing the sync-up time to 2 min. However, it did not work.
![Screenshot 2023-09-24 225953](https://github.com/coldenate/rollover-daily-todos/assets/144189642/1cffe842-bd1c-459d-aeb9-e2adab2bc013)
![Screenshot 2023-09-24 230134](https://github.com/coldenate/rollover-daily-todos/assets/144189642/bed7fae6-9c5f-4da6-93f2-3de9f07b8995)

**Comment by coldenate** [comment] 2023-09-25 11:45
Did you make the `this is a new to do to test the daily doc portal
• September 20th, 2023` **not** in a daily document? If so, that will make it not rollover. I actually have that as a feature coming out in 1.5.0 where you can rollover from anywhere, but I haven't published it yet. 😅 (4e44f1c2b924034007d853309954e95ab0b6dd07)
1. go to the rem
2. run /move and type in September 20th in the modal
3. Rerun /rollover

Right now, RTD only looks in the Daily Documents for todos, and its functionality doesn't yet include references. Great idea though!!

**Comment by coldenate** [comment] 2023-09-25 11:47
As for the Auto Rollover Syncups, I'm so glad it worked! :)
I think our suspicions were right. Given that it said `null` at first, the syncedStorage was broken and caused an error. I'll keep this issue open so I can remember to make a fix for that. 
Let's double check and work through the reference thingy. 
Thanks so much for responding and helping out! I really appreciate the responses. please feel free to open issues for anything else in the future!

**Comment by anumeha-in** [comment] 2023-09-25 15:40
Thanks so much Nate. The RDT has worked, except the todos from elsewhere as you mentioned. I will wait for that enhancement :-)

**Comment by coldenate** [comment] 2023-09-25 17:46
Nice!! No problem!

**Closed as completed** 2023-09-25 17:46 UTC
Labels: question
